stages:
  - preparation
  - build
  - test

prepare:
  stage: preparation
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - shared-windows
  script:
    - choco feature enable -n allowGlobalConfirmation
    - choco install qt5-default boost-msvc-14.2 cmake
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - "C://Qt"
      - "C://local"
      - "C:/Program Files/CMake"

compile:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script: -\
      cd ..
      mkdir build
      cd build
      "C:/Program Files/CMake/bin/cmake" $CI_PROJECT_DIR
      "C:/Program Files/CMake/bin/cmake" --build . --target stellarlink
      echo "BUILD_PATH=$(Get-Location).Path" >> compile.env
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - "C://Qt"
      - "C://local"
      - "C:/Program Files/CMake"
    reports:
      dotenv: compile.env
  needs: 
    - job: "prepare"
      artifacts: true


run:
  stage: test
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script:
    - $BUILD_PATH\stellarlink.exe
    - echo "Tested"
  needs: 
    - job: "compile"
      artifacts: true
