stages:
  - preparation
  - build
  - test

prepare:
  stage: preparation
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - shared-windows
  script:
    - choco feature enable -n allowGlobalConfirmation
    - choco install qt5-default boost-msvc-14.2

compile:
  stage: build
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script: 
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --target stellarlink
  needs: ["prepare"]


run:
  stage: test
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script:
    - build\stellarlink.exe
    - echo "Tested"
  needs: ["prepare", "compile"]
