stages:
  - preparation_compile
  - test

variables:
  BUILD_PATH: ""

prepare_compile:
  stage: preparation_compile
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - shared-windows
  script:
    - |
      # Install Dependencies
      choco feature enable -n allowGlobalConfirmation
      choco install qt5-default qbs boost-msvc-14.2 cmake
      
      # Compile
      Get-ChildItem
      cd ..
      mkdir build
      cd build
      $BUILD_PATH=$(Get-Location).Path
      & "C:/Program Files/CMake/bin/cmake.exe" stellarlink
      & "C:/Program Files/CMake/bin/cmake.exe" --build . --target stellarlink
      cd ..
  artifacts:
     name: $CI_JOB_NAME
     paths:
       - "C:/GitLab-Runner/builds/JosephBisso/build"
  
run:
  stage: test
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script:
    - |
      & "C:/GitLab-Runner/builds/JosephBisso/build/stellarlink.exe"
      echo "Tested"
  needs: 
    - job: "prepare_compile"
      artifacts: true
