stages:
  - preparation_compile
  - test

variables:
  BUILD_PATH: ""

prepare_compile:
  stage: preparation_compile
  variables: 
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - shared-windows
  script:
    - |
      # Install Dependencies
      choco feature enable -n allowGlobalConfirmation
      choco install qt5-default boost-msvc-14.2 cmake
      
      # Compile
      cd ..
      mkdir build
      cd build
      & "C:/Program Files/CMake/bin/cmake.exe" $CI_PROJECT_DIR
      & "C:/Program Files/CMake/bin/cmake.exe" --build . --target stellarlink
      cd $CI_PROJECT_DIR
      $BUILD_PATH=$(Get-Location).Path
  artifacts:
     name: $CI_JOB_NAME
     paths:
       - "$BUILD_PATH"
  
run:
  stage: test
  variables:
    GIT_STRATEGY: none
  tags:
    - shared-windows
  script:
    - |
      & "$BUILD_PATH/stellarlink.exe"
      echo "Tested"
  needs: 
    - job: "prepare_compile"
      artifacts: true
